apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: behave
spec:
  workspaces:
    - name: source
  description: >-
    This task can be used to perform bdd tests with behave.
  params:
    - name: base-url
      description: The url of the application to test
      type: string
    - name: wait-seconds
      description: The number of seconds to wait for a reply
      type: string
      default: "60"
    - name: driver
      description: The web driver to use (chrome or firefox)
      type: string
      default: "chrome"
  steps:
    - name: behave
      image: quay.io/rofrano/pipeline-selenium
      workingDir: $(workspaces.source.path)
      env:
       - name: BASE_URL
         value: $(params.base-url)
       - name: WAIT_SECONDS
         value: $(params.wait-seconds)
       - name: DRIVER
         value: $(params.driver)
      script: |
        #!/bin/bash
        set -e
        export PATH=$PATH:$HOME/.local/bin:

        echo "***** Installing dependencies *****"
        if [ -e "poetry.lock" ]; then
          echo "Found poetry.lock file: using poetry"
          python -m pip install poetry poetry-plugin-export
          poetry export --with=dev -f requirements.txt --output requirements.txt
        elif [ -e "Pipfile" ]; then
          echo "Found Pipfile file: using pipenv ..."
          python -m pip install --upgrade pip pipenv
          pipenv requirements --dev > requirements.txt
        fi
        python -m pip install --user -r requirements.txt

        echo "***** Running Tests *****"
        behave