apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REF
      default: master
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: git-clone-1-19-0
      params:
        - name: URL
          value: https://github.com/CSCI-GA-2820-SU25-001/orders
        - name: REVISION
          value: $(params.GIT_REF)
      taskRef:
        params:
          - name: name
            value: git-clone-1-19-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: pytest-env
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pytest-env }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: pylint
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pylint }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy-image
      params:
      - name: image-name
        value: $(params.IMAGE_NAME)
      - name: manifest-dir
        value: k8s
      runAfter:
      - buildah-1-19-0
      taskRef:
        kind: Task
        name: deploy-image
      workspaces:
      - name: source
        workspace: pipeline-workspace