apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: GIT_REPO
      default: https://github.com/CSCI-GA-2820-SU25-001/orders
      description: The Git repository to clone
    - name: GIT_REF
      default: master
      description: The reference (branch or ref)
    - name: APP_NAME
      default: orders
      description: App name, used to name the container image
    - name: IMAGE_URL
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest
      description: URL to upload our built container image to
    - name: BEHAVE_URL
      default: https://$(params.APP_NAME)-$(context.pipelineRun.namespace).apps.rm2.thpm.p1.openshiftapps.com/
      description: URL to point the behave tests to. This is the format of the Pod URL created by the deploy-image task.
  tasks:
    - name: git-clone-1-19-0
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
      taskRef:
        params:
          - name: name
            value: git-clone-1-19-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: pytest-env
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pytest-env }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: pylint
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pylint }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: buildah-1-19-0
      params:
        - name: IMAGE
          value: $(params.IMAGE_URL)
      runAfter: [pytest-env, pylint]
      taskRef:
        params:
          - name: name
            value: buildah-1-19-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy-image
      params:
        - name: image-name
          value: $(params.IMAGE_URL)
      runAfter: [buildah-1-19-0]
      taskRef: { name: deploy-image }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: behave
      params:
        - name: base-url
          value: $(params.BEHAVE_URL)
      runAfter: [deploy-image]
      taskRef: { name: behave }
      workspaces:
        - name: source
          workspace: pipeline-workspace
