apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REF
      default: master
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: git-clone-1-19-0
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
      taskRef:
        params:
          - name: name
            value: git-clone-1-19-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: pytest-env
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pytest-env }
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: pylint
      runAfter: [git-clone-1-19-0]
      taskRef: { name: pylint }
      workspaces:
        - name: source
          workspace: pipeline-workspace
