apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  description: Pipeline with custom git-clone step
  params:
    - name: GIT_REPO
      type: string
      description: The Git repository to clone
    - name: GIT_REF
      type: string
      default: "main"
      description: The Git branch, tag, or commit to check out
  workspaces:
    - name: pipeline-workspace
      description: Shared workspace for all pipeline tasks
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: repo-url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
      workspaces:
        - name: output
          workspace: pipeline-workspace